/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiRouteImport } from './routes/api'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as SecurityRouteImport } from './routes/security'
import { Route as AccessPointsIndexRouteImport } from './routes/access-points/index'
import { Route as AccessPointsSysIdRouteImport } from './routes/access-points/$sysId'
import { Route as DatabasesIndexRouteImport } from './routes/databases/index'
import { Route as DatabasesSysIdRouteImport } from './routes/databases/$sysId'
import { Route as ServersIndexRouteImport } from './routes/servers/index'
import { Route as ServersSysIdRouteImport } from './routes/servers/$sysId'
import { Route as SwitchesIndexRouteImport } from './routes/switches/index'
import { Route as SwitchesSysIdRouteImport } from './routes/switches/$sysId'
import { Route as ApiPublicSplatRouteImport } from './routes/api/public/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRoute = ApiRouteImport.update({
  id: '/api',
  path: '/api',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityRoute = SecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessPointsIndexRoute = AccessPointsIndexRouteImport.update({
  id: '/access-points/',
  path: '/access-points/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessPointsSysIdRoute = AccessPointsSysIdRouteImport.update({
  id: '/access-points/$sysId',
  path: '/access-points/$sysId',
  getParentRoute: () => rootRouteImport,
} as any)
const DatabasesIndexRoute = DatabasesIndexRouteImport.update({
  id: '/databases/',
  path: '/databases/',
  getParentRoute: () => rootRouteImport,
} as any)
const DatabasesSysIdRoute = DatabasesSysIdRouteImport.update({
  id: '/databases/$sysId',
  path: '/databases/$sysId',
  getParentRoute: () => rootRouteImport,
} as any)
const ServersIndexRoute = ServersIndexRouteImport.update({
  id: '/servers/',
  path: '/servers/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServersSysIdRoute = ServersSysIdRouteImport.update({
  id: '/servers/$sysId',
  path: '/servers/$sysId',
  getParentRoute: () => rootRouteImport,
} as any)
const SwitchesIndexRoute = SwitchesIndexRouteImport.update({
  id: '/switches/',
  path: '/switches/',
  getParentRoute: () => rootRouteImport,
} as any)
const SwitchesSysIdRoute = SwitchesSysIdRouteImport.update({
  id: '/switches/$sysId',
  path: '/switches/$sysId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSplatRoute = ApiPublicSplatRouteImport.update({
  id: '/public/$',
  path: '/public/$',
  getParentRoute: () => ApiRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api': typeof ApiRouteWithChildren
  '/auth': typeof AuthRoute
  '/privacy': typeof PrivacyRoute
  '/security': typeof SecurityRoute
  '/access-points/$sysId': typeof AccessPointsSysIdRoute
  '/databases/$sysId': typeof DatabasesSysIdRoute
  '/servers/$sysId': typeof ServersSysIdRoute
  '/switches/$sysId': typeof SwitchesSysIdRoute
  '/access-points/': typeof AccessPointsIndexRoute
  '/databases/': typeof DatabasesIndexRoute
  '/servers/': typeof ServersIndexRoute
  '/switches/': typeof SwitchesIndexRoute
  '/api/public/$': typeof ApiPublicSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api': typeof ApiRouteWithChildren
  '/auth': typeof AuthRoute
  '/privacy': typeof PrivacyRoute
  '/security': typeof SecurityRoute
  '/access-points/$sysId': typeof AccessPointsSysIdRoute
  '/databases/$sysId': typeof DatabasesSysIdRoute
  '/servers/$sysId': typeof ServersSysIdRoute
  '/switches/$sysId': typeof SwitchesSysIdRoute
  '/access-points': typeof AccessPointsIndexRoute
  '/databases': typeof DatabasesIndexRoute
  '/servers': typeof ServersIndexRoute
  '/switches': typeof SwitchesIndexRoute
  '/api/public/$': typeof ApiPublicSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api': typeof ApiRouteWithChildren
  '/auth': typeof AuthRoute
  '/privacy': typeof PrivacyRoute
  '/security': typeof SecurityRoute
  '/access-points/$sysId': typeof AccessPointsSysIdRoute
  '/databases/$sysId': typeof DatabasesSysIdRoute
  '/servers/$sysId': typeof ServersSysIdRoute
  '/switches/$sysId': typeof SwitchesSysIdRoute
  '/access-points/': typeof AccessPointsIndexRoute
  '/databases/': typeof DatabasesIndexRoute
  '/servers/': typeof ServersIndexRoute
  '/switches/': typeof SwitchesIndexRoute
  '/api/public/$': typeof ApiPublicSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api'
    | '/auth'
    | '/privacy'
    | '/security'
    | '/access-points/$sysId'
    | '/databases/$sysId'
    | '/servers/$sysId'
    | '/switches/$sysId'
    | '/access-points/'
    | '/databases/'
    | '/servers/'
    | '/switches/'
    | '/api/public/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api'
    | '/auth'
    | '/privacy'
    | '/security'
    | '/access-points/$sysId'
    | '/databases/$sysId'
    | '/servers/$sysId'
    | '/switches/$sysId'
    | '/access-points'
    | '/databases'
    | '/servers'
    | '/switches'
    | '/api/public/$'
  id:
    | '__root__'
    | '/'
    | '/api'
    | '/auth'
    | '/privacy'
    | '/security'
    | '/access-points/$sysId'
    | '/databases/$sysId'
    | '/servers/$sysId'
    | '/switches/$sysId'
    | '/access-points/'
    | '/databases/'
    | '/servers/'
    | '/switches/'
    | '/api/public/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiRoute: typeof ApiRouteWithChildren
  AuthRoute: typeof AuthRoute
  PrivacyRoute: typeof PrivacyRoute
  SecurityRoute: typeof SecurityRoute
  AccessPointsSysIdRoute: typeof AccessPointsSysIdRoute
  DatabasesSysIdRoute: typeof DatabasesSysIdRoute
  ServersSysIdRoute: typeof ServersSysIdRoute
  SwitchesSysIdRoute: typeof SwitchesSysIdRoute
  AccessPointsIndexRoute: typeof AccessPointsIndexRoute
  DatabasesIndexRoute: typeof DatabasesIndexRoute
  ServersIndexRoute: typeof ServersIndexRoute
  SwitchesIndexRoute: typeof SwitchesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api': {
      id: '/api'
      path: '/api'
      fullPath: '/api'
      preLoaderRoute: typeof ApiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security': {
      id: '/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof SecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/access-points/': {
      id: '/access-points/'
      path: '/access-points'
      fullPath: '/access-points/'
      preLoaderRoute: typeof AccessPointsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/access-points/$sysId': {
      id: '/access-points/$sysId'
      path: '/access-points/$sysId'
      fullPath: '/access-points/$sysId'
      preLoaderRoute: typeof AccessPointsSysIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/databases/': {
      id: '/databases/'
      path: '/databases'
      fullPath: '/databases/'
      preLoaderRoute: typeof DatabasesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/databases/$sysId': {
      id: '/databases/$sysId'
      path: '/databases/$sysId'
      fullPath: '/databases/$sysId'
      preLoaderRoute: typeof DatabasesSysIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servers/': {
      id: '/servers/'
      path: '/servers'
      fullPath: '/servers/'
      preLoaderRoute: typeof ServersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servers/$sysId': {
      id: '/servers/$sysId'
      path: '/servers/$sysId'
      fullPath: '/servers/$sysId'
      preLoaderRoute: typeof ServersSysIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/switches/': {
      id: '/switches/'
      path: '/switches'
      fullPath: '/switches/'
      preLoaderRoute: typeof SwitchesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/switches/$sysId': {
      id: '/switches/$sysId'
      path: '/switches/$sysId'
      fullPath: '/switches/$sysId'
      preLoaderRoute: typeof SwitchesSysIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/$': {
      id: '/api/public/$'
      path: '/public/$'
      fullPath: '/api/public/$'
      preLoaderRoute: typeof ApiPublicSplatRouteImport
      parentRoute: typeof ApiRoute
    }
  }
}

interface ApiRouteChildren {
  ApiPublicSplatRoute: typeof ApiPublicSplatRoute
}

const ApiRouteChildren: ApiRouteChildren = {
  ApiPublicSplatRoute: ApiPublicSplatRoute,
}

const ApiRouteWithChildren = ApiRoute._addFileChildren(ApiRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiRoute: ApiRouteWithChildren,
  AuthRoute: AuthRoute,
  PrivacyRoute: PrivacyRoute,
  SecurityRoute: SecurityRoute,
  AccessPointsSysIdRoute: AccessPointsSysIdRoute,
  DatabasesSysIdRoute: DatabasesSysIdRoute,
  ServersSysIdRoute: ServersSysIdRoute,
  SwitchesSysIdRoute: SwitchesSysIdRoute,
  AccessPointsIndexRoute: AccessPointsIndexRoute,
  DatabasesIndexRoute: DatabasesIndexRoute,
  ServersIndexRoute: ServersIndexRoute,
  SwitchesIndexRoute: SwitchesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
