/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as ApiRouteImport } from './routes/api'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as SecurityRouteImport } from './routes/security'
import { Route as AuthenticatedAccessPointsIndexRouteImport } from './routes/_authenticated/access-points/index'
import { Route as AuthenticatedAccessPointsSysIdRouteImport } from './routes/_authenticated/access-points/$sysId'
import { Route as AuthenticatedDatabasesIndexRouteImport } from './routes/_authenticated/databases/index'
import { Route as AuthenticatedDatabasesSysIdRouteImport } from './routes/_authenticated/databases/$sysId'
import { Route as AuthenticatedServersIndexRouteImport } from './routes/_authenticated/servers/index'
import { Route as AuthenticatedServersSysIdRouteImport } from './routes/_authenticated/servers/$sysId'
import { Route as AuthenticatedSwitchesIndexRouteImport } from './routes/_authenticated/switches/index'
import { Route as AuthenticatedSwitchesSysIdRouteImport } from './routes/_authenticated/switches/$sysId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRoute = ApiRouteImport.update({
  id: '/api',
  path: '/api',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityRoute = SecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAccessPointsIndexRoute =
  AuthenticatedAccessPointsIndexRouteImport.update({
    id: '/access-points/',
    path: '/access-points/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAccessPointsSysIdRoute =
  AuthenticatedAccessPointsSysIdRouteImport.update({
    id: '/access-points/$sysId',
    path: '/access-points/$sysId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDatabasesIndexRoute =
  AuthenticatedDatabasesIndexRouteImport.update({
    id: '/databases/',
    path: '/databases/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDatabasesSysIdRoute =
  AuthenticatedDatabasesSysIdRouteImport.update({
    id: '/databases/$sysId',
    path: '/databases/$sysId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedServersIndexRoute =
  AuthenticatedServersIndexRouteImport.update({
    id: '/servers/',
    path: '/servers/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedServersSysIdRoute =
  AuthenticatedServersSysIdRouteImport.update({
    id: '/servers/$sysId',
    path: '/servers/$sysId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSwitchesIndexRoute =
  AuthenticatedSwitchesIndexRouteImport.update({
    id: '/switches/',
    path: '/switches/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSwitchesSysIdRoute =
  AuthenticatedSwitchesSysIdRouteImport.update({
    id: '/switches/$sysId',
    path: '/switches/$sysId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api': typeof ApiRoute
  '/auth': typeof AuthRoute
  '/privacy': typeof PrivacyRoute
  '/security': typeof SecurityRoute
  '/access-points/$sysId': typeof AuthenticatedAccessPointsSysIdRoute
  '/databases/$sysId': typeof AuthenticatedDatabasesSysIdRoute
  '/servers/$sysId': typeof AuthenticatedServersSysIdRoute
  '/switches/$sysId': typeof AuthenticatedSwitchesSysIdRoute
  '/access-points/': typeof AuthenticatedAccessPointsIndexRoute
  '/databases/': typeof AuthenticatedDatabasesIndexRoute
  '/servers/': typeof AuthenticatedServersIndexRoute
  '/switches/': typeof AuthenticatedSwitchesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api': typeof ApiRoute
  '/auth': typeof AuthRoute
  '/privacy': typeof PrivacyRoute
  '/security': typeof SecurityRoute
  '/access-points/$sysId': typeof AuthenticatedAccessPointsSysIdRoute
  '/databases/$sysId': typeof AuthenticatedDatabasesSysIdRoute
  '/servers/$sysId': typeof AuthenticatedServersSysIdRoute
  '/switches/$sysId': typeof AuthenticatedSwitchesSysIdRoute
  '/access-points': typeof AuthenticatedAccessPointsIndexRoute
  '/databases': typeof AuthenticatedDatabasesIndexRoute
  '/servers': typeof AuthenticatedServersIndexRoute
  '/switches': typeof AuthenticatedSwitchesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/api': typeof ApiRoute
  '/auth': typeof AuthRoute
  '/privacy': typeof PrivacyRoute
  '/security': typeof SecurityRoute
  '/_authenticated/access-points/$sysId': typeof AuthenticatedAccessPointsSysIdRoute
  '/_authenticated/databases/$sysId': typeof AuthenticatedDatabasesSysIdRoute
  '/_authenticated/servers/$sysId': typeof AuthenticatedServersSysIdRoute
  '/_authenticated/switches/$sysId': typeof AuthenticatedSwitchesSysIdRoute
  '/_authenticated/access-points/': typeof AuthenticatedAccessPointsIndexRoute
  '/_authenticated/databases/': typeof AuthenticatedDatabasesIndexRoute
  '/_authenticated/servers/': typeof AuthenticatedServersIndexRoute
  '/_authenticated/switches/': typeof AuthenticatedSwitchesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api'
    | '/auth'
    | '/privacy'
    | '/security'
    | '/access-points/$sysId'
    | '/databases/$sysId'
    | '/servers/$sysId'
    | '/switches/$sysId'
    | '/access-points/'
    | '/databases/'
    | '/servers/'
    | '/switches/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api'
    | '/auth'
    | '/privacy'
    | '/security'
    | '/access-points/$sysId'
    | '/databases/$sysId'
    | '/servers/$sysId'
    | '/switches/$sysId'
    | '/access-points'
    | '/databases'
    | '/servers'
    | '/switches'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/api'
    | '/auth'
    | '/privacy'
    | '/security'
    | '/_authenticated/access-points/$sysId'
    | '/_authenticated/databases/$sysId'
    | '/_authenticated/servers/$sysId'
    | '/_authenticated/switches/$sysId'
    | '/_authenticated/access-points/'
    | '/_authenticated/databases/'
    | '/_authenticated/servers/'
    | '/_authenticated/switches/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  ApiRoute: typeof ApiRoute
  AuthRoute: typeof AuthRoute
  PrivacyRoute: typeof PrivacyRoute
  SecurityRoute: typeof SecurityRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api': {
      id: '/api'
      path: '/api'
      fullPath: '/api'
      preLoaderRoute: typeof ApiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security': {
      id: '/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof SecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/access-points/': {
      id: '/_authenticated/access-points/'
      path: '/access-points'
      fullPath: '/access-points/'
      preLoaderRoute: typeof AuthenticatedAccessPointsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/access-points/$sysId': {
      id: '/_authenticated/access-points/$sysId'
      path: '/access-points/$sysId'
      fullPath: '/access-points/$sysId'
      preLoaderRoute: typeof AuthenticatedAccessPointsSysIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/databases/': {
      id: '/_authenticated/databases/'
      path: '/databases'
      fullPath: '/databases/'
      preLoaderRoute: typeof AuthenticatedDatabasesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/databases/$sysId': {
      id: '/_authenticated/databases/$sysId'
      path: '/databases/$sysId'
      fullPath: '/databases/$sysId'
      preLoaderRoute: typeof AuthenticatedDatabasesSysIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/servers/': {
      id: '/_authenticated/servers/'
      path: '/servers'
      fullPath: '/servers/'
      preLoaderRoute: typeof AuthenticatedServersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/servers/$sysId': {
      id: '/_authenticated/servers/$sysId'
      path: '/servers/$sysId'
      fullPath: '/servers/$sysId'
      preLoaderRoute: typeof AuthenticatedServersSysIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/switches/': {
      id: '/_authenticated/switches/'
      path: '/switches'
      fullPath: '/switches/'
      preLoaderRoute: typeof AuthenticatedSwitchesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/switches/$sysId': {
      id: '/_authenticated/switches/$sysId'
      path: '/switches/$sysId'
      fullPath: '/switches/$sysId'
      preLoaderRoute: typeof AuthenticatedSwitchesSysIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAccessPointsSysIdRoute: typeof AuthenticatedAccessPointsSysIdRoute
  AuthenticatedDatabasesSysIdRoute: typeof AuthenticatedDatabasesSysIdRoute
  AuthenticatedServersSysIdRoute: typeof AuthenticatedServersSysIdRoute
  AuthenticatedSwitchesSysIdRoute: typeof AuthenticatedSwitchesSysIdRoute
  AuthenticatedAccessPointsIndexRoute: typeof AuthenticatedAccessPointsIndexRoute
  AuthenticatedDatabasesIndexRoute: typeof AuthenticatedDatabasesIndexRoute
  AuthenticatedServersIndexRoute: typeof AuthenticatedServersIndexRoute
  AuthenticatedSwitchesIndexRoute: typeof AuthenticatedSwitchesIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAccessPointsSysIdRoute: AuthenticatedAccessPointsSysIdRoute,
  AuthenticatedDatabasesSysIdRoute: AuthenticatedDatabasesSysIdRoute,
  AuthenticatedServersSysIdRoute: AuthenticatedServersSysIdRoute,
  AuthenticatedSwitchesSysIdRoute: AuthenticatedSwitchesSysIdRoute,
  AuthenticatedAccessPointsIndexRoute: AuthenticatedAccessPointsIndexRoute,
  AuthenticatedDatabasesIndexRoute: AuthenticatedDatabasesIndexRoute,
  AuthenticatedServersIndexRoute: AuthenticatedServersIndexRoute,
  AuthenticatedSwitchesIndexRoute: AuthenticatedSwitchesIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  ApiRoute: ApiRoute,
  AuthRoute: AuthRoute,
  PrivacyRoute: PrivacyRoute,
  SecurityRoute: SecurityRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
